(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }})("level",
{ "height":24,
 "layers":[
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":24,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":32,
         "x":0,
         "y":0
        }, 
        {
         "height":24,
         "image":"..\/images\/map1.jpg",
         "name":"images\/map1",
         "opacity":1,
         "type":"imagelayer",
         "visible":true,
         "width":32,
         "x":0,
         "y":0
        }, 
        {
         "height":24,
         "name":"Game",
         "objects":[
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":158,
                 "x":160,
                 "y":159
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":88,
                 "x":607,
                 "y":163
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":60,
                 "x":546,
                 "y":163
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":60,
                 "x":515,
                 "y":193
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":60,
                 "x":482,
                 "y":225
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":80,
                 "x":417,
                 "y":258
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":30,
                 "x":449,
                 "y":352
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":60,
                 "x":162,
                 "y":258
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":91,
                 "x":0,
                 "y":259
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":91,
                 "x":0,
                 "y":416
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":191,
                 "x":161,
                 "y":448
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":124,
                 "x":673,
                 "y":452
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":123,
                 "x":608,
                 "y":547
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":123,
                 "x":798,
                 "y":548
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":188,
                 "x":735,
                 "y":645
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":91,
                 "x":98,
                 "y":643
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":91,
                 "x":33,
                 "y":514
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":91,
                 "x":162,
                 "y":355
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":62,
                 "x":290,
                 "y":291
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":91,
                 "x":737,
                 "y":256
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":70,
                 "x":788,
                 "y":292
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":91,
                 "x":931,
                 "y":258
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":157,
                 "x":865,
                 "y":419
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":184,
                 "x":740,
                 "y":96
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":163,
                 "x":254,
                 "y":224
                }, 
                {
                 "height":18,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":64,
                 "x":192,
                 "y":581
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":159,
                 "x":285,
                 "y":578
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":59,
                 "x":417,
                 "y":642
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":84,
                 "x":516,
                 "y":580
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":47,
                 "x":548,
                 "y":485
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":60,
                 "x":417,
                 "y":452
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":165,
                 "x":579,
                 "y":355
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":59,
                 "x":290,
                 "y":675
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":91,
                 "x":258,
                 "y":707
                }, 
                {
                 "height":262,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":21,
                 "x":3,
                 "y":6
                }, 
                {
                 "height":346,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":22,
                 "x":2,
                 "y":419
                }, 
                {
                 "height":339,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":23,
                 "x":998,
                 "y":425
                }, 
                {
                 "height":262,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":21,
                 "x":1000,
                 "y":1
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":995,
                 "x":12,
                 "y":744
                }, 
                {
                 "height":41,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"player",
                 "visible":true,
                 "width":34,
                 "x":33,
                 "y":370
                }, 
                {
                 "height":104,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"player",
                 "visible":true,
                 "width":42,
                 "x":883,
                 "y":311
                }, 
                {
                 "height":53,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"player",
                 "visible":true,
                 "width":34,
                 "x":218,
                 "y":103
                }, 
                {
                 "height":41,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"player",
                 "visible":true,
                 "width":37,
                 "x":654,
                 "y":699
                }, 
                {
                 "height":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"floor",
                 "visible":true,
                 "width":61,
                 "x":418,
                 "y":100
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":32,
         "x":0,
         "y":0
        }],
 "orientation":"orthogonal",
 "properties":
    {

    },
 "tileheight":32,
 "tilesets":[],
 "tilewidth":32,
 "version":1,
 "width":32
});